[package]
name = "oxiced"
description = "An iced themeing library"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0-or-later"

[dependencies]
arboard = "3.4.1"
iced_core = { git = "https://github.com/Azorlogh/iced", rev = "47af5890d8cf80b8bfd5909eee1ef3b1d5c05421" }
iced_runtime = { git = "https://github.com/Azorlogh/iced", rev = "47af5890d8cf80b8bfd5909eee1ef3b1d5c05421" }
iced_wgpu = { git = "https://github.com/Azorlogh/iced", rev = "47af5890d8cf80b8bfd5909eee1ef3b1d5c05421" }
iced_widget = { git = "https://github.com/Azorlogh/iced", rev = "47af5890d8cf80b8bfd5909eee1ef3b1d5c05421" }
iced_renderer = { git = "https://github.com/Azorlogh/iced", features = [
	"wgpu",
], rev = "47af5890d8cf80b8bfd5909eee1ef3b1d5c05421" }
iced_layershell = "0.9.0"
once_cell = "1.20"
serde = "1.0"
toml = "0.8"
xdg = "2.5.2"
zbus = "5.2.0"
