[package]
name = "oxiced"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13", features = ["advanced", "canvas"] }
iced_layershell = { git = "https://github.com/waycrate/exwlshelleventloop", branch = "iced_13" }
once_cell = "1.19.0"
serde = "1.0.204"
toml = "0.8.14"
xdg = "2.5.2"
