[package]
name = "oxiced"
description = "An iced themeing library"
version = "0.4.1"
edition = "2024"
license = "LGPL-3.0-or-later"

[dependencies]
iced = { version = "0.13.1", features = ["advanced", "canvas", "svg"] }
iced_layershell = "0.13.6"
once_cell = "1.21.3"
serde = "1.0.219"
toml = "0.8.22"
xdg = "3.0.0"
