[package]
name = "oxiced"
description = "An iced themeing library"
version = "0.4.0"
edition = "2024"
license = "LGPL-3.0-or-later"

[dependencies]
iced = { version = "0.13", features = ["advanced", "canvas", "svg"] }
iced_layershell = "0.13.5"
once_cell = "1.21.3"
serde = "1.0.219"
toml = "0.8.22"
xdg = "2.5.2"
