[package]
name = "oxiced"
description = "An iced themeing library"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0-or-later"

[dependencies]
arboard = "3.4.1"
iced = { version = "0.13", features = ["advanced", "canvas"] }
iced_layershell = "0.9"
iced_wgpu = "0.13"
iced_renderer = { version = "0.13", features = ["wgpu"] }
iced_widget = "0.13"
iced_runtime = "0.13"
iced_core = "0.13"
iced_tiny_skia = "0.13"
once_cell = "1.19.0"
serde = "1.0.204"
toml = "0.8.14"
xdg = "2.5.2"
zbus = "5.1.0"
