[package]
name = "oxiced"
description = "An iced themeing library"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0-or-later"

[dependencies]
arboard = "3.4.1"
iced = { version = "0.13", features = ["advanced", "canvas"] }
iced_layershell = "0.9"
iced_tiny_skia = "0.13"
iced_core = { git = "https://github.com/tzemanovic/iced.git", rev = "a594033be7d3ed2ec20967de93bf62c4013088f3" }
iced_runtime = { git = "https://github.com/tzemanovic/iced.git", rev = "a594033be7d3ed2ec20967de93bf62c4013088f3" }
iced_wgpu = { git = "https://github.com/tzemanovic/iced.git", rev = "a594033be7d3ed2ec20967de93bf62c4013088f3" }
iced_widget = { git = "https://github.com/tzemanovic/iced.git", rev = "a594033be7d3ed2ec20967de93bf62c4013088f3" }
iced_renderer = { git = "https://github.com/tzemanovic/iced.git", rev = "a594033be7d3ed2ec20967de93bf62c4013088f3", features = [
	"wgpu",
] }
once_cell = "1.19.0"
serde = "1.0.204"
toml = "0.8.14"
xdg = "2.5.2"
zbus = "5.1.0"
